
version: '3'
services:
  app:
    build:
      args:
          user: laurent
          uid: 1000
      context: ./docker
      dockerfile: Dockerfile
    image: linky
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default

  scheduler:
    image: linky
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: ./docker/bin/run-scheduler.sh
    networks:
      - default

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=linky
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres-data:
